### ISSUE TITLE
transfer

### ISSUE THREAD

**Issue by kerjaairdrop43** [downygg/OceanClaimer#13]
bang itu transfer ocean isi adressnya kita dimana?

**Comment by downygg** [comment]
lupa commit index ny, udah di tambah index ny

**Comment by kerjaairdrop43** [comment]
> lupa commit index ny, udah di tambah index ny

bang riquest kalau ga keberatan ditambahin yang make privare key soalnya memonit ane ilang

**Comment by downygg** [comment]
> > lupa commit index ny, udah di tambah index ny
> 
> bang riquest kalau ga keberatan ditambahin yang make privare key soalnya memonit ane ilang

sudah di tambahkan
