### ISSUE TITLE
Multi Account

### ISSUE THREAD

**Issue by BerkahJaya09** [downygg/OceanClaimer#14]
Bang bisa 3 account ga?

**Comment by BerkahJaya09** [comment]
Thanks Bang, kalo yang transfer ocean buat apa bang?

**Comment by kerjaairdrop43** [comment]
> Thanks Bang, kalo yang transfer ocean buat apa bang?

jangan lupa donasi ke owner buar ucapan tq

**Comment by downygg** [comment]
> Thanks Bang, kalo yang transfer ocean buat apa bang?

buat kirim semua ocean yg ada di wallet tuyul ke wallet utama.

**Comment by kerjaairdrop43** [comment]
> > Thanks Bang, kalo yang transfer ocean buat apa bang?
> 
> buat kirim semua ocean yg ada di wallet tuyul ke wallet utama.

![image](https://github.com/downygg/OceanClaimer/assets/152783749/9b569914-9fe5-4780-8840-b1487f5dd27f)
mau auto send ovean kok eror bang make private  key

**Comment by kerjaairdrop43** [comment]
dah bisa ane dah donasi 1 sui sama kirim lewat email juga ip sama link tx

**Comment by njmond** [comment]
Berati yang seed pharse ke satu itu arah transfernya kesitu bang?

**Comment by downygg** [comment]
> > > Thanks Bang, kalo yang transfer ocean buat apa bang?
> > 
> > 
> > buat kirim semua ocean yg ada di wallet tuyul ke wallet utama.
> 
> ![image](https://private-user-images.githubusercontent.com/152783749/332345109-9b569914-9fe5-4780-8840-b1487f5dd27f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODM0MTAsIm5iZiI6MTcxNjI4MzExMCwicGF0aCI6Ii8xNTI3ODM3NDkvMzMyMzQ1MTA5LTliNTY5OTE0LTlmZTUtNDc4MC04ODQwLWIxNDg3ZjVkZDI3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwOTE4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTc0MjBiM2ZmZWZjOTg5MDAyMTI2OWJjMmMyZmM3NjVmOGZkY2E0OWVjM2U3ZTY2MDJkMGNlYmJjZmJkYTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6bAaS7Ywpk7uPLYvRcEZ9k3BABZ3eDYebPavTgNenIc) mau auto send ovean kok eror bang make private key

ini udah bisa kah?

**Comment by kerjaairdrop43** [comment]
> Berati yang seed pharse ke satu itu arah transfernya kesitu bang?

nanti ada inputan masuin adress lu kalau dah ke unlock. gua tadi nyoba sebelum di lock sama admin nya wkwkwk

**Comment by downygg** [comment]
> > > > > Thanks Bang, kalo yang transfer ocean buat apa bang?
> > > > 
> > > > 
> > > > buat kirim semua ocean yg ada di wallet tuyul ke wallet utama.
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/152783749/332345109-9b569914-9fe5-4780-8840-b1487f5dd27f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODM0MTAsIm5iZiI6MTcxNjI4MzExMCwicGF0aCI6Ii8xNTI3ODM3NDkvMzMyMzQ1MTA5LTliNTY5OTE0LTlmZTUtNDc4MC04ODQwLWIxNDg3ZjVkZDI3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwOTE4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTc0MjBiM2ZmZWZjOTg5MDAyMTI2OWJjMmMyZmM3NjVmOGZkY2E0OWVjM2U3ZTY2MDJkMGNlYmJjZmJkYTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6bAaS7Ywpk7uPLYvRcEZ9k3BABZ3eDYebPavTgNenIc) mau auto send ovean kok eror bang make private key
> > 
> > 
> > ini udah bisa kah?
> 
> udah tapi di lock bang dah ane kirim 1 sui. dah kirim email juga

udah ke unlock kan?

**Comment by kerjaairdrop43** [comment]
> > > > > > Thanks Bang, kalo yang transfer ocean buat apa bang?
> > > > > 
> > > > > 
> > > > > buat kirim semua ocean yg ada di wallet tuyul ke wallet utama.
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/152783749/332345109-9b569914-9fe5-4780-8840-b1487f5dd27f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODM0MTAsIm5iZiI6MTcxNjI4MzExMCwicGF0aCI6Ii8xNTI3ODM3NDkvMzMyMzQ1MTA5LTliNTY5OTE0LTlmZTUtNDc4MC04ODQwLWIxNDg3ZjVkZDI3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwOTE4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTc0MjBiM2ZmZWZjOTg5MDAyMTI2OWJjMmMyZmM3NjVmOGZkY2E0OWVjM2U3ZTY2MDJkMGNlYmJjZmJkYTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6bAaS7Ywpk7uPLYvRcEZ9k3BABZ3eDYebPavTgNenIc) mau auto send ovean kok eror bang make private key
> > > 
> > > 
> > > ini udah bisa kah?
> > 
> > 
> > udah tapi di lock bang dah ane kirim 1 sui. dah kirim email juga
> 
> udah ke unlock kan?

![image](https://github.com/downygg/OceanClaimer/assets/152783749/1aef008e-e178-43e3-ad61-3fcc324271b9)
belom

**Comment by downygg** [comment]
> > > > > > > Thanks Bang, kalo yang transfer ocean buat apa bang?
> > > > > > 
> > > > > > 
> > > > > > buat kirim semua ocean yg ada di wallet tuyul ke wallet utama.
> > > > > 
> > > > > 
> > > > > ![image](https://private-user-images.githubusercontent.com/152783749/332345109-9b569914-9fe5-4780-8840-b1487f5dd27f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODM0MTAsIm5iZiI6MTcxNjI4MzExMCwicGF0aCI6Ii8xNTI3ODM3NDkvMzMyMzQ1MTA5LTliNTY5OTE0LTlmZTUtNDc4MC04ODQwLWIxNDg3ZjVkZDI3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwOTE4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTc0MjBiM2ZmZWZjOTg5MDAyMTI2OWJjMmMyZmM3NjVmOGZkY2E0OWVjM2U3ZTY2MDJkMGNlYmJjZmJkYTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6bAaS7Ywpk7uPLYvRcEZ9k3BABZ3eDYebPavTgNenIc) mau auto send ovean kok eror bang make private key
> > > > 
> > > > 
> > > > ini udah bisa kah?
> > > 
> > > 
> > > udah tapi di lock bang dah ane kirim 1 sui. dah kirim email juga
> > 
> > 
> > udah ke unlock kan?
> 
> ![image](https://private-user-images.githubusercontent.com/152783749/332366374-1aef008e-e178-43e3-ad61-3fcc324271b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODM5NzQsIm5iZiI6MTcxNjI4MzY3NCwicGF0aCI6Ii8xNTI3ODM3NDkvMzMyMzY2Mzc0LTFhZWYwMDhlLWUxNzgtNDNlMy1hZDYxLTNmY2MzMjQyNzFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwOTI3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGQ3MDBkNzRkNGZiZWQwM2YyMTdkODJkNDY0MDJjYjBmM2MzOTIwNmIyZDExYWFlZTExZjc3Zjg0ZmYwYTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4qoneQDgL0A7argMsGYZEmR46agZFwCXerWh9XPhlkQ) belom

masuk spam

**Comment by kerjaairdrop43** [comment]
> > > > > > > > Thanks Bang, kalo yang transfer ocean buat apa bang?
> > > > > > > 
> > > > > > > 
> > > > > > > buat kirim semua ocean yg ada di wallet tuyul ke wallet utama.
> > > > > > 
> > > > > > 
> > > > > > ![image](https://private-user-images.githubusercontent.com/152783749/332345109-9b569914-9fe5-4780-8840-b1487f5dd27f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODM0MTAsIm5iZiI6MTcxNjI4MzExMCwicGF0aCI6Ii8xNTI3ODM3NDkvMzMyMzQ1MTA5LTliNTY5OTE0LTlmZTUtNDc4MC04ODQwLWIxNDg3ZjVkZDI3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwOTE4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTc0MjBiM2ZmZWZjOTg5MDAyMTI2OWJjMmMyZmM3NjVmOGZkY2E0OWVjM2U3ZTY2MDJkMGNlYmJjZmJkYTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6bAaS7Ywpk7uPLYvRcEZ9k3BABZ3eDYebPavTgNenIc) mau auto send ovean kok eror bang make private key
> > > > > 
> > > > > 
> > > > > ini udah bisa kah?
> > > > 
> > > > 
> > > > udah tapi di lock bang dah ane kirim 1 sui. dah kirim email juga
> > > 
> > > 
> > > udah ke unlock kan?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/152783749/332366374-1aef008e-e178-43e3-ad61-3fcc324271b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODM5NzQsIm5iZiI6MTcxNjI4MzY3NCwicGF0aCI6Ii8xNTI3ODM3NDkvMzMyMzY2Mzc0LTFhZWYwMDhlLWUxNzgtNDNlMy1hZDYxLTNmY2MzMjQyNzFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwOTI3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGQ3MDBkNzRkNGZiZWQwM2YyMTdkODJkNDY0MDJjYjBmM2MzOTIwNmIyZDExYWFlZTExZjc3Zjg0ZmYwYTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4qoneQDgL0A7argMsGYZEmR46agZFwCXerWh9XPhlkQ) belom
> 
> masuk spam

dah ane balas emailnya

**Comment by njmond** [comment]
> > Berati yang seed pharse ke satu itu arah transfernya kesitu bang?
> 
> transfer ke akun utama biar ga capek

Berati yang di source-mnemonic.json cuma di isi seed pharse akun uyul aja bang?
Cek email bang dah ane donate

**Comment by downygg** [comment]
> > > Berati yang seed pharse ke satu itu arah transfernya kesitu bang?
> > 
> > 
> > transfer ke akun utama biar ga capek
> 
> Berati yang di source-mnemonic.json cuma di isi seed pharse akun uyul aja bang? Cek email bang dah ane donate

betul

**Comment by njmond** [comment]
> > > > Berati yang seed pharse ke satu itu arah transfernya kesitu bang?
> > > 
> > > 
> > > transfer ke akun utama biar ga capek
> > 
> > 
> > Berati yang di source-mnemonic.json cuma di isi seed pharse akun uyul aja bang? Cek email bang dah ane donate
> 
> betul

Siapp bang , cek email bang IP akhiran 200

**Comment by downygg** [comment]
> > > > > Berati yang seed pharse ke satu itu arah transfernya kesitu bang?
> > > > 
> > > > 
> > > > transfer ke akun utama biar ga capek
> > > 
> > > 
> > > Berati yang di source-mnemonic.json cuma di isi seed pharse akun uyul aja bang? Cek email bang dah ane donate
> > 
> > 
> > betul
> 
> Siapp bang , cek email bang IP akhiran 200

cek emailnya

**Comment by njmond** [comment]
> > > > > > Berati yang seed pharse ke satu itu arah transfernya kesitu bang?
> > > > > 
> > > > > 
> > > > > transfer ke akun utama biar ga capek
> > > > 
> > > > 
> > > > Berati yang di source-mnemonic.json cuma di isi seed pharse akun uyul aja bang? Cek email bang dah ane donate
> > > 
> > > 
> > > betul
> > 
> > 
> > Siapp bang , cek email bang IP akhiran 200
> 
> cek emailnya

Udah ane bales bang
