### ISSUE TITLE
 fetch failed

### ISSUE THREAD

**Issue by kerjaairdrop43** [downygg/OceanClaimer#16]
kok sering  fetch failed kenapa ya bang

**Comment by downygg** [comment]
coba ss

**Comment by kerjaairdrop43** [comment]
> coba ss
![image](https://github.com/downygg/OceanClaimer/assets/152783749/79fac1ad-6489-47f3-ae3e-f0c28f7c4776)

mau send ocean sama claim juga gitu bang sering munculnya

**Comment by downygg** [comment]
node js versi berapa?

**Comment by kerjaairdrop43** [comment]
> node js versi berapa?

![image](https://github.com/downygg/OceanClaimer/assets/152783749/65f21beb-f7ea-4bfb-90c1-d9c192a45929)
make terbaru bang

**Comment by downygg** [comment]
error dari chain nya

**Comment by kerjaairdrop43** [comment]
> error dari chain nya

bang kenapa ente ga nambahin langsung multi send sui buat fee wkwkwk

**Comment by kerjaairdrop43** [comment]
> oke menarik, soon

di tunggu karna tgl 26 ada update seperti ini

1. Sistemnya akan diupgrade sehingga kedepannya akan meminimalisir error
2. Team detect banyak player yang menggunakan bot sehingga tim akan mengimplementasikan anti-bot
3. Sistem FCFS akan dihapus
4. Akan ada sistem sybil
5. Next event Ocean Treasure Box akan diadakan mulai tanggal 28 May - 31 May

**Comment by downygg** [comment]
artinya apa tuh? abu kah?

**Comment by kerjaairdrop43** [comment]
> artinya apa tuh? abu kah?

keknya bakal ada captcha setiap claim nanti bang jadi gak pada make bot

**Comment by kerjaairdrop43** [comment]
> artinya apa tuh? abu kah?

scnya minta upgrade wkwkwk

**Comment by bimaindrawans** [comment]
> > artinya apa tuh? abu kah?
> 
> keknya bakal ada captcha setiap claim nanti bang jadi gak pada make bot

Kalau nanti ada captcha, siapa tau bisa di implementasiin capsolver (nanti setiap user yg pake suruh beli api key nya sendiri), (bisa versi audio / chaptcha gambar, rekomen & murah), btw bang botnya 
[21/05/24 15:57:10] Failed To Run. Please Update Your Script.

**Comment by downygg** [comment]
re run all

**Comment by kerjaairdrop43** [comment]
> re run all

bang kalau buy sc yang on 24 jam sampe end ada? yang ga nunggu upgrade

**Comment by downygg** [comment]
> > re run all
> 
> bang kalau buy sc yang on 24 jam sampe end ada? yang ga nunggu upgrade

bisa, email aj
