### ISSUE TITLE
API belum aktif

### ISSUE THREAD

**Issue by cholis321** [downygg/OceanClaimer#38]
saya donasi di 2 akun gmail, API belum aktif

mohon untuk diaktifkan

API yang satu, min donasi tertulis 0.003, tetapi di bot 0.005 jadi belum bisa

untuk akun yang lain saya donasi 0.07, dan belum aktif sepertinya

**Comment by downygg** [comment]
apikey ny email tanpa @gmail.com

**Comment by cholis321** [comment]
sudah, tapi tertulis donasi lebih dari 0.005 SUI kan kredit lebiih dari 5k, kenapa saya kok ga lebih dari 5k padahal lebih dari 0.005 SUI bang

**Comment by downygg** [comment]
Kalau kirim lebih dari 0.005 maka maksimal 5k credit

**Comment by cholis321** [comment]
oalah begitu, oke bang
