### ISSUE TITLE
send sui

### ISSUE THREAD

**Issue by kerjaairdrop43** [downygg/OceanClaimer#39]
bang kok send sui nya ga bisa di pake bang

**Comment by kerjaairdrop43** [comment]
![image](https://github.com/downygg/OceanClaimer/assets/152783749/7f8b1619-bae7-45d8-89d5-94cf919d4e94)


ga bisa semua dah make email make ip juga

**Comment by satinex** [comment]
> ![image](https://private-user-images.githubusercontent.com/152783749/333392037-7f8b1619-bae7-45d8-89d5-94cf919d4e94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTUzODYsIm5iZiI6MTcxNjUxNTA4NiwicGF0aCI6Ii8xNTI3ODM3NDkvMzMzMzkyMDM3LTdmOGIxNjE5LWJhZTctNDVkOC04OWQ1LTk0Y2Y5MTlkNGU5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwMTQ0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGI0YmRkMDQwNmI4Yzk3ZWIyYmJiZjE2ZDJjYWU1YzE5MGFjNTVlYzRhYjAyMTViZWFjNzc0ZDk5NDYzM2Q0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WiXc0-WBuoR59ws8jQ9JruiN22vB-TROTii0xMtoIqY)
> 
> ga bisa semua dah make email make ip juga

bayar itu mas, kirim sui ke owner nya terus kirim buktinya ke email itu

**Comment by kerjaairdrop43** [comment]
> > ![image](https://private-user-images.githubusercontent.com/152783749/333392037-7f8b1619-bae7-45d8-89d5-94cf919d4e94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTUzODYsIm5iZiI6MTcxNjUxNTA4NiwicGF0aCI6Ii8xNTI3ODM3NDkvMzMzMzkyMDM3LTdmOGIxNjE5LWJhZTctNDVkOC04OWQ1LTk0Y2Y5MTlkNGU5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwMTQ0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGI0YmRkMDQwNmI4Yzk3ZWIyYmJiZjE2ZDJjYWU1YzE5MGFjNTVlYzRhYjAyMTViZWFjNzc0ZDk5NDYzM2Q0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WiXc0-WBuoR59ws8jQ9JruiN22vB-TROTii0xMtoIqY)
> > ga bisa semua dah make email make ip juga
> 
> bayar itu mas, kirim sui ke owner nya terus kirim buktinya ke email itu

udah bro

**Comment by downygg** [comment]
update ke versi v1.1.0
