### ISSUE TITLE
getaddrinfo ENOTFOUND fullnode.mainnet.sui.io

### ISSUE THREAD

**Issue by cholis321** [downygg/OceanClaimer#40]
Apa solusi ketika muncul notif seperti itu?

**Comment by downygg** [comment]
harus claim 1 kali di bot ocean nya

**Comment by cholis321** [comment]
oh harus manual dulu ya

**Comment by downygg** [comment]
claim pertama kali harus manual karena itu registrasi pengguna ke bot ocean nya

**Comment by cholis321** [comment]
oke bang
