### ISSUE TITLE
lapor

### ISSUE THREAD

**Issue by kerjaairdrop43** [downygg/OceanClaimer#45]
![image](https://github.com/downygg/OceanClaimer/assets/152783749/74ac3e20-cf6c-4f29-aaad-4b4f0e05a538)

kenapa ini bang

**Comment by downygg** [comment]
pake delay berapa menit ? error di rpc sui nya

**Comment by downygg** [comment]
> ![image](https://private-user-images.githubusercontent.com/152783749/333575101-74ac3e20-cf6c-4f29-aaad-4b4f0e05a538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTE5MTQsIm5iZiI6MTcxNjU1MTYxNCwicGF0aCI6Ii8xNTI3ODM3NDkvMzMzNTc1MTAxLTc0YWMzZTIwLWNmNmMtNGYyOS1hYWFkLTRiNGYwZTA1YTUzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxMTUzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDg0YzQxNDE2MTIwN2NjMzdlNDdmY2U5YThhZDFiOGNmYzMyNDY3NmFiNjA4NzRjMjFjZjA5ZmJjZGZhNTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.asoLQDiJfAud8g2TbN7hnCORrHfu5-F-nEv_Pdav_z8)
> 
> kenapa ini bang

kalau error paling atas itu akun nya belum claim pertama kali

**Comment by kerjaairdrop43** [comment]
> > ![image](https://private-user-images.githubusercontent.com/152783749/333575101-74ac3e20-cf6c-4f29-aaad-4b4f0e05a538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTE5MTQsIm5iZiI6MTcxNjU1MTYxNCwicGF0aCI6Ii8xNTI3ODM3NDkvMzMzNTc1MTAxLTc0YWMzZTIwLWNmNmMtNGYyOS1hYWFkLTRiNGYwZTA1YTUzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxMTUzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDg0YzQxNDE2MTIwN2NjMzdlNDdmY2U5YThhZDFiOGNmYzMyNDY3NmFiNjA4NzRjMjFjZjA5ZmJjZGZhNTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.asoLQDiJfAud8g2TbN7hnCORrHfu5-F-nEv_Pdav_z8)
> > kenapa ini bang
> 
> kalau error paling atas itu akun nya belum claim pertama kali

itu akun dah old semua bang dari awal abang post di github

**Comment by downygg** [comment]
pindah device, error di rpc sui nya. Disini lancar

**Comment by kerjaairdrop43** [comment]
> pindah device, error di rpc sui nya. Disini lancar

keknya emang pc ane kentang bang wkwkwk di termux malah enak banget. makasih banyak bang
