### ISSUE TITLE
arrow key gabisa di pake

### ISSUE THREAD

**Issue by goddamnarmdone** [downygg/OceanClaimer#46]
ini gimana caranya ngatasin arrow key gabisa dipake bang? udh nyoba beberapa tutroial masih gabisa

**Comment by downygg** [comment]
pake terminal apa ?

**Comment by goddamnarmdone** [comment]
cmd

**Comment by downygg** [comment]
coba download terminal cmder, pastikan lagi ketika `npm i` semua package sukses terinstal dan minimal requirement nodejs v18 up

**Comment by goddamnarmdone** [comment]
masih tetep gabisa di cmder juga node v20

**Comment by downygg** [comment]
arrow key pas milih menu nya kan ?

**Comment by goddamnarmdone** [comment]
yaps

**Comment by downygg** [comment]
menu nya nampil ?

**Comment by goddamnarmdone** [comment]
ada menunya cuma gabisa diarahin kebawah

**Comment by downygg** [comment]
coba tes pakai on screen keyboard

**Comment by goddamnarmdone** [comment]
tetep bingung sendiri malah wkwk

**Comment by downygg** [comment]
coba delete dulu node_modules sama package-lock.json nya, lalu npm i ulang. Kalau gabisa juga berrti masalah di console nya. Skalian send txid ny biar di refund

**Comment by goddamnarmdone** [comment]
okee wait bang

**Comment by downygg** [comment]
bisa di coba https://stackoverflow.com/questions/55753151/cant-use-arrow-keys-in-git-bash-windows

**Comment by goddamnarmdone** [comment]
AtMHe3kq6GBpET2hs9mvi5U4RKCAzpb39hmxSoAhTjhj

oke dicoba bang

**Comment by downygg** [comment]
ini maksud ny gimana? arrow key gabisa di pake tapi kredit nya berkurang? brrti program nya jalan kan?

**Comment by goddamnarmdone** [comment]
![image](https://github.com/downygg/OceanClaimer/assets/160879464/d629372f-a73e-4035-b96e-36968b5fad65)

gabisa diapa2in ngerun eror karna bukan private key

**Comment by downygg** [comment]
oooh berarti cuma enter2 aja ya. Sudah di refund. Mungkin bisa di cari tau dulu penyebab nya karena ini dari device nya

**Comment by goddamnarmdone** [comment]
okee masih dicari solusinya

**Comment by Sazharr911** [comment]
Bang kok run di vps gk bisa ya?
Udah ikutin command nya jg, klo vps bisa mau donasi

**Comment by downygg** [comment]
> Bang kok run di vps gk bisa ya? Udah ikutin command nya jg, klo vps bisa mau donasi



> Bang kok run di vps gk bisa ya? Udah ikutin command nya jg, klo vps bisa mau donasi

ss gabisa nya gimana?

**Comment by ahmad246642** [comment]
> > Bang kok run di vps gk bisa ya? Udah ikutin command nya jg, klo vps bisa mau donasi
> 
> > Bang kok run di vps gk bisa ya? Udah ikutin command nya jg, klo vps bisa mau donasi
> 
> ss gabisa nya gimana?

bang bikin bot yang VivaFtn bang claim 1 jam sekali

**Comment by fakhris18** [comment]
harus bayar y bg?

**Comment by downygg** [comment]
> harus bayar y bg?

ga harus, bisa pake api key ocean yang gratis nya tapi credit nya cepat habis karena di gangbang

**Comment by goddamnarmdone** [comment]
done bang bisa coba npm install keypress / npm install readline terus restart device
