### ISSUE TITLE
Cara Setting Send MASS SUI

### ISSUE THREAD

**Issue by cholis321** [downygg/OceanClaimer#54]
ini cara input addres wallet tujuan dimana ya?

**Comment by downygg** [comment]
masukkan address tujuan nya di source.json, format nya :
```
[
 "address1",
"address2"
]
```

**Comment by cholis321** [comment]
masukinnya di folder apa bg?

**Comment by downygg** [comment]
File source.json

**Comment by cholis321** [comment]
maksudnya di foler V1.1.0 kah?

**Comment by downygg** [comment]
pake yg versi terbaru

**Comment by downygg** [comment]
fixed new commit. Upate aja source index.js nya
