### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by njmond** [downygg/OceanClaimer#55]
Dah send lewat form bang cek

**Comment by downygg** [comment]
approved

**Comment by njmond** [comment]
> approved

Masih invalid

**Comment by downygg** [comment]
- Your mail : example@gmail.com
- Your API Key : example (without @gmail.com)

**Comment by njmond** [comment]
> * Your mail : [example@gmail.com](mailto:example@gmail.com)
> * Your API Key : example (without @gmail.com)

Udah pake gmail

**Comment by downygg** [comment]
> > * Your mail : [example@gmail.com](mailto:example@gmail.com)
> > * Your API Key : example (without @gmail.com)
> 
> Udah pake gmail

itu dibaca ketarangan nya **without @gmail.com**

**Comment by njmond** [comment]
> > > * Your mail : [example@gmail.com](mailto:example@gmail.com)
> > > * Your API Key : example (without @gmail.com)
> > 
> > 
> > Udah pake gmail
> 
> itu dibaca ketarangan nya **without @gmail.com**

Oh iya udah bang
