### ISSUE TITLE
Send Mass Sui

### ISSUE THREAD

**Issue by ricky10p** [downygg/OceanClaimer#56]
Input your source private key ini isi apa bang?

**Comment by downygg** [comment]
private key wallet pengirim

**Comment by ricky10p** [comment]
Tetap gak bisa bang,kenapa ya?

**Comment by ricky10p** [comment]
![Uploading IMG_20240525_185029.jpg…]()

**Comment by ricky10p** [comment]
![IMG_20240525_185029](https://github.com/downygg/OceanClaimer/assets/80503241/b08043fb-5e7f-4148-b85d-1df959c455da)

**Comment by downygg** [comment]
pastikan pas input priv key ga ada spasi atau karakter lain

**Comment by downygg** [comment]
> Input your source private key ini isi apa bang?

update ke versi terbaru ya.
