### ISSUE TITLE
Info 

### ISSUE THREAD

**Issue by Plowester1** [downygg/OceanClaimer#60]
Kalo di termux kenapa auto claim nya gak jalan ya? Sekali claim udah stuck Remaining nya 30 menit program, udah 30 menit gak mau claim auto termux nya tetap on di background

**Comment by downygg** [comment]
pastikan masih runing program ny

**Comment by Plowester1** [comment]
Sbntr di coba 2 jam kedepan

**Comment by downygg** [comment]
atau bisa pake pm2

**Comment by Yinka71** [comment]
> atau bisa pake pm2

Kalo mau pm abang kemana ya

**Comment by downygg** [comment]
> > atau bisa pake pm2
> 
> Kalo mau pm abang kemana ya

bukan, itu maksud nya package nya pm2. Cari google aja pm2 nodejs

**Comment by Plowester1** [comment]
Aman, kirimin link google mau donate credit

**Comment by downygg** [comment]
cek di program nya, masukin asal aja di apikey nya biar muncul informasi nya

**Comment by Plowester1** [comment]
Interval nya gabisa jadi 2 jam bro 😙

**Comment by downygg** [comment]
> Interval nya gabisa jadi 2 jam bro 😙

noted nnti di update lagi buat yang 2 jam sekali
