### ISSUE TITLE
SEND

### ISSUE THREAD

**Issue by Lutfayy** [downygg/OceanClaimer#63]
auto send gabisa kah?

**Comment by downygg** [comment]
gabisa gimana ? apakah sudah update ke versi terbaru ?

**Comment by Lutfayy** [comment]
Mass Sender SUI biar bisa drain fee ya bg kwkw

**Comment by downygg** [comment]
lah kocak, itu maksud nya buat kirim sui ke wallet tuyul. itu juga dikirim ke wallet yang ada di source.json

**Comment by downygg** [comment]
fix karena ada issue #56

**Comment by Lutfayy** [comment]
di grup grup juga banyak yg kena drain

**Comment by downygg** [comment]
sebelum pake punya gua itu pake punya siapa dulu kocak

**Comment by Lutfayy** [comment]
katanya dari downygg

**Comment by downygg** [comment]
pastikan dulu itu dia pake dari punya gua  pure atau ganti2 punya orang

**Comment by ahmad246642** [comment]
> di grup grup juga banyak yg kena drain

grup mana bang
