### ISSUE TITLE
Google docs udah pernah submit mau donate credit

### ISSUE THREAD

**Issue by Plowester1** [downygg/OceanClaimer#65]
![Screenshot_20240526-015715](https://github.com/downygg/OceanClaimer/assets/170664076/2af58773-58a6-43ba-b8f5-067eab408c80)

**Comment by downygg** [comment]
pake gmail lain karena 1 tx = 1 apikey

**Comment by Plowester1** [comment]
Di buat submit another respond aja bro 🙂

**Comment by downygg** [comment]
> Di buat submit another respond aja bro 🙂

banyak spam

**Comment by yunitaaa2131** [comment]
> Reference in new i

bg per 100.000 kredit berapa sui

**Comment by yunitaaa2131** [comment]
> > Di buat submit another respond aja bro 🙂
> 
> banyak spam

bg per 100.000 kredit berapa sui

**Comment by downygg** [comment]
> > > Di buat submit another respond aja bro 🙂
> > 
> > 
> > banyak spam
> 
> bg per 100.000 kredit berapa sui

5 SUI = 9999999 credits

**Comment by yunitaaa2131** [comment]
> > > > Di buat submit another respond aja bro 🙂
> > > 
> > > 
> > > banyak spam
> > 
> > 
> > bg per 100.000 kredit berapa sui
> 
> 5 SUI = 9999999 credits

999.999 kredit brapa sui bg ,soalnya banyak akun hehe

**Comment by downygg** [comment]
itu udah di bilang 5 SUI

**Comment by yunitaaa2131** [comment]
> itu udah di bilang 5 SUI

itu 9.999.999 (9 jt bg) .

**Comment by downygg** [comment]
> > itu udah di bilang 5 SUI
> 
> itu 9.999.999 (9 jt bg) .

benar atau sampai airdrop nya selesai

**Comment by zaydens** [comment]
gmn cara donate 5 sui bang?
