### ISSUE TITLE
Mass Sender SUI

### ISSUE THREAD

**Issue by yunitaaa2131** [downygg/OceanClaimer#66]
![iocean](https://github.com/downygg/OceanClaimer/assets/170827220/e20a89ab-0f41-4008-89b4-0db4747aafec)

**Comment by downygg** [comment]
masukan address tujuan nya di source.json

**Comment by yunitaaa2131** [comment]
jadi kalau buat claim  masukin pharse'
kalau buat send masukin address?

**Comment by downygg** [comment]
benar sekali
