### ISSUE TITLE
Apikey

### ISSUE THREAD

**Issue by mamangbenu** [downygg/OceanClaimer#69]
Bg untuk regist donasi buat apikey udah closed ya?

**Comment by mamangbenu** [comment]
Minta link form dong bg

**Comment by downygg** [comment]
Saat ini sudah close karena sudah terlalu banyak. Kalau garapan ny masih lanjut, nnti akan dibuka lagi menggantikan user yg credit ny udh habis

**Comment by mamangbenu** [comment]
Harus mantau berati ya bg

**Comment by zaydens** [comment]
permisi mas saya butuh apikey untuk menjalankan botnya, dimana saya bisa donate untuk apikey nya? karna yang kmrn sudah habis creditnya
tolong di respon
