### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by ryandhikacc** [downygg/OceanClaimer#7]
How can i study the source code? Is it sort of encrypted? Why do you need to obfuscate it? Idk if this one doesnt send over your phrase key if i cant read the code.

**Comment by downygg** [comment]
If you are unsure about this code, please leave it and create your own code. You can sniff your network, if you found this code sending your phrase to me, you can show me here.

**Comment by ryandhikacc** [comment]
Thanks for the feedback, certainly I'm not sure about the code, and if you intend to decrypt your code, perhaps you built it in a compiled way in the first place? Isn't github intended for others to know what's behind the programs they use?

No offense here, as I am genuinely curious and want to learn how you interact with the sui chain without involving a telegram login like the other wave claimer bots on github.

**Comment by ryandhikacc** [comment]
Thanks for the feedback, certainly I'm not sure about the code, and if you intend to decrypt your code, perhaps you built it in a compiled way in the first place? Isn't github intended for others to know what's behind the programs they use?

No offense here, as I am genuinely curious and want to learn how you interact with the sui chain without involving a telegram login like the other wave claimer bots on github.
