### ISSUE TITLE
API

### ISSUE THREAD

**Issue by cholis321** [downygg/OceanClaimer#75]
Bagus, tutup aja API nya sementara. Biar buktikan SC nya memang trust. Saya pakai masih aman. Soon semoga buka tapi selective aja deh coba bang Developers.

**Comment by downygg** [comment]
siap bang, makasi support nya

**Comment by ardika24** [comment]
saya udah pake aman aaja dari awal sebelum v1.1 
emang yg fud tolol, asal comot dari repo orang habis itu yg di salahin malah repo sini

**Comment by Harisannan** [comment]
next update mungkin bisa di buat agar langsung klaim mana yang bisa klaim

**Comment by cholis321** [comment]
Kapan bisa beli API lagi bang?

**Comment by downygg** [comment]
Udah bisa tp emailny harus beda biar bisa submit lgi

Pada Minggu, 26 Mei 2024, cholis321 ***@***.***> menulis:
