### ISSUE TITLE
Auto send ocean problem

### ISSUE THREAD

**Issue by satinex** [downygg/OceanClaimer#76]
ini kenapa ya 
? [26/05/24 13:31:35] Ocean Balance : 194
? [26/05/24 13:31:36] Status : InsufficientCoinBalance in command 1

**Comment by downygg** [comment]
sui nya ada ga ?

**Comment by satinex** [comment]
ada 1, gass feenya berapa emg?

> sui nya ada ga ?

**Comment by downygg** [comment]
tergantung load chain nya, tpi itu kya ga mencapai minimum amount yang disetting. Atau klo pilih send all ocean brrti balance ny kena pembulatan

**Comment by satinex** [comment]
> tergantung load chain nya, tpi itu kya ga mencapai minimum amount yang disetting. Atau klo pilih send all ocean brrti balance ny kena pembulatan

minimum amountnya berapa emg bang?

**Comment by downygg** [comment]
itu pas pilih menu awal ada di set minimum each account ga? atau pilih yg send all ocean ?

**Comment by satinex** [comment]
itu errornya send all bang, tapi kalo custom amount sendiri work

**Comment by downygg** [comment]
coba custom maks 100 atau dibawah 100 aja, kya dari chain nya maksimal kirim ny 100 ocean per transaksi

**Comment by satinex** [comment]
ohh berarti kalo di atas 100 ga bisa send all ya?
soalnya tadi coba kirim custom100 bisa, terus coba lagi kirim sisa 97 ocean terus milih send all baru bisa

**Comment by downygg** [comment]
> ohh berarti kalo di atas 100 ga bisa send all ya? soalnya tadi coba kirim custom100 bisa, terus coba lagi kirim sisa 97 ocean terus milih send all baru bisa

kyanya dari chain nya gitu
