### ISSUE TITLE
Status : Please make first claim at your Wave Wallet Bot or refil your SUI Balance.

### ISSUE THREAD

**Issue by brimob-sowax** [downygg/OceanClaimer#78]
om abis ada update kemarin kok beberapa akun ada yang eror ya ?

"Status : Please make first claim at your Wave Wallet Bot or refil your SUI Balance."

padahal ini bukan akun baru dan kemarin2 lancar ( claim / wd ), saldo SUI juga cukup ( 0.05 )

**Comment by downygg** [comment]
Coba claim dulu di bot ny

**Comment by brimob-sowax** [comment]
claim yg kayak gimana om ?

**Comment by downygg** [comment]
Claim manual dulu

**Comment by brimob-sowax** [comment]
maaf caranya gimana om ?

**Comment by downygg** [comment]
Ya claim manual di bot telegram ny. Buka ocean bot > claim

**Comment by kerjaairdrop43** [comment]
> maaf caranya gimana om ?

caranya lu login di bot make parshe yang eror terus claim manual

**Comment by brimob-sowax** [comment]
> Ya claim manual di bot telegram ny. Buka ocean bot > claim

padahal ini udah akun lama kok harus klaim ulang ya

**Comment by kerjaairdrop43** [comment]
> > Ya claim manual di bot telegram ny. Buka ocean bot > claim
> 
> padahal ini udah akun lama kok harus klaim ulang ya

di cek dulu siapa tau akun lu yang eror . gua aman aja dari pagi

**Comment by brimob-sowax** [comment]
> > maaf caranya gimana om ?
> 
> caranya lu login di bot make parshe yang eror terus claim manual

maksudnya login di tele ?
udah saya coba manual claim di tele trs claim lagi pake bot masih eror aja

**Comment by downygg** [comment]
> > Ya claim manual di bot telegram ny. Buka ocean bot > claim
> 
> padahal ini udah akun lama kok harus klaim ulang ya

Coba dulu gitu. Ini yg lu maksud akun telegram ny udah lama atau gimana? Kalo akun telegram udh lama tapi belum ada interaksi claim berarti masih baru di ocean bot

**Comment by brimob-sowax** [comment]
> > > Ya claim manual di bot telegram ny. Buka ocean bot > claim
> > 
> > 
> > padahal ini udah akun lama kok harus klaim ulang ya
> 
> Coba dulu gitu. Ini yg lu maksud akun telegram ny udah lama atau gimana? Kalo akun telegram udh lama tapi belum ada interaksi claim berarti masih baru di ocean bot

bukan akun telenya om, akun ocean nya
kl akun baru bikin kan emang harus claim dulu dari tele baru claim lewat bot

**Comment by downygg** [comment]
Boat ny udh upgrade ?

**Comment by brimob-sowax** [comment]
> Boat ny udh upgrade ?

blm sih om, masih yg 2h
semua tuyul saya nggak ada yg up boat, tp yg eror cuma beberapa aja

**Comment by downygg** [comment]
Coba di claim dulu 1 yg error , lalu jalankan program bot ny lagi. Waktu tunggu ny udah muncul ga? Nnti report kesini

**Comment by brimob-sowax** [comment]
> Coba di claim dulu 1 yg error , lalu jalankan program bot ny lagi. Waktu tunggu ny udah muncul ga? Nnti report kesini

barusan saya lakuin, masih sama om
 "Status : Please make first claim at your Wave Wallet Bot or refil your SUI Balance."
 
 dari tadi pagi saya nyari2 penyebabnya blm nemu, apa akun eror ya ?

**Comment by downygg** [comment]
Kyanya akun ny error itu. Cuma kalo boleh 1 akun yg error itu gua beli sama pharse ny buat investigasi lanjut

**Comment by brimob-sowax** [comment]
> Kyanya akun ny error itu. Cuma kalo boleh 1 akun yg error itu gua beli sama pharse ny buat investigasi lanjut

nggak usah beli om, saya kasih akun aja yg paling baru bikin hari ini
kirim kemana ?

**Comment by downygg** [comment]
Kirim ke email babi.anjing26@gmail.com
Butuh 1 akun aj dulu buat mastiin error ny

**Comment by kerjaairdrop43** [comment]
> > Kyanya akun ny error itu. Cuma kalo boleh 1 akun yg error itu gua beli sama pharse ny buat investigasi lanjut
> 
> nggak usah beli om, saya kasih akun aja yg paling baru bikin hari ini kirim kemana ?

di email aja wkwkwk

**Comment by brimob-sowax** [comment]
> Kirim ke email [babi.anjing26@gmail.com](mailto:babi.anjing26@gmail.com) Butuh 1 akun aj dulu buat mastiin error

done om

**Comment by brimob-sowax** [comment]
> > > Kyanya akun ny error itu. Cuma kalo boleh 1 akun yg error itu gua beli sama pharse ny buat investigasi lanjut
> > 
> > 
> > nggak usah beli om, saya kasih akun aja yg paling baru bikin hari ini kirim kemana ?
> 
> di email aja wkwkwk

siappp paham om, tp email kan ada alamatnya

**Comment by ahmad246642** [comment]
> Kirim ke email [babi.anjing26@gmail.com](mailto:babi.anjing26@gmail.com) Butuh 1 akun aj dulu buat mastiin error ny

bkin claim 1jam skali bang sama 2 jam

**Comment by downygg** [comment]
> > Kirim ke email [babi.anjing26@gmail.com](mailto:babi.anjing26@gmail.com) Butuh 1 akun aj dulu buat mastiin error ny
> 
> bkin claim 1jam skali bang sama 2 jam

Noted. Sering pantau aja repo ny sama cek commit terakhir karena update minor ga akan ada notif di bot ny

**Comment by brimob-sowax** [comment]
> > > Kirim ke email [babi.anjing26@gmail.com](mailto:babi.anjing26@gmail.com) Butuh 1 akun aj dulu buat mastiin error ny
> > 
> > 
> > bkin claim 1jam skali bang sama 2 jam
> 
> Noted. Sering pantau aja repo ny sama cek commit terakhir karena update minor ga akan ada notif di bot ny

tolong cek email dong om, akun tadi udah beres tp yg lainnya masih eror
jadi bukan dari filenya yg eror om

**Comment by downygg** [comment]
Masalah di rpc sui nya

**Comment by brimob-sowax** [comment]
> Masalah di rpc sui nya

jadi bukan akun saya yg eror ya om ?
akunnya si om ada juga yg kena eror kayak gitu kah ?

**Comment by downygg** [comment]
Belum pernah error sih sejauh ini aman2 aja tapi tuyul ny cuma dikit

**Comment by brimob-sowax** [comment]
oke siap makasih om, tolong cek email lagi ya om
