### ISSUE TITLE
gg

### ISSUE THREAD

**Issue by kerjaairdrop43** [downygg/OceanClaimer#8]
padaahal enak yang awal bang lebih lancar daripada ini malah banyak eror

**Comment by kerjaairdrop43** [comment]
==== Wait Until 1 Hour(s), 15 minute(s), 8 second(s) ====

bagian itu di edit 3-5 menit aja bang karena ga semua akun claimnnya samaan

**Comment by downygg** [comment]
> padaahal enak yang awal bang lebih lancar daripada ini malah banyak eror

error gimana ?

> ==== Wait Until 1 Hour(s), 15 minute(s), 8 second(s) ====
> 
> bagian itu di edit 3-5 menit aja bang karena ga semua akun claimnnya samaan

itu looping berdasarkan waktu tunggu tercepat dari daftar akun, kalau di akun nya ada 2 menit brrti next loop nya 2 menit lagi

**Comment by kerjaairdrop43** [comment]
> > padaahal enak yang awal bang lebih lancar daripada ini malah banyak eror
> 
> error gimana ?
> 
> > ==== Wait Until 1 Hour(s), 15 minute(s), 8 second(s) ====
> > bagian itu di edit 3-5 menit aja bang karena ga semua akun claimnnya samaan
> 
> itu looping berdasarkan waktu tunggu tercepat dari daftar akun, kalau di akun nya ada 2 menit brrti next loop nya 2 menit lagi

done bang dah ane samain semua akun jadi enak makasih banyak bang

**Comment by kerjaairdrop43** [comment]
> > padaahal enak yang awal bang lebih lancar daripada ini malah banyak eror
> 
> error gimana ?
> 
> > ==== Wait Until 1 Hour(s), 15 minute(s), 8 second(s) ====
> > bagian itu di edit 3-5 menit aja bang karena ga semua akun claimnnya samaan
> 
> itu looping berdasarkan waktu tunggu tercepat dari daftar akun, kalau di akun nya ada 2 menit brrti next loop nya 2 menit lagi

bang eror minta upgrade sc
