### ISSUE TITLE
masih error kah bang?

### ISSUE THREAD

**Issue by ahmad246642** [downygg/OceanClaimer#82]
![Uploading Screenshot_20240527-173029.jpg…]()

**Comment by downygg** [comment]
Ga kliatan gambar ny

**Comment by Yinka71** [comment]
> Ga kliatan gambar ny

Ada update baru kah min?

**Comment by downygg** [comment]
Betul, update aja

**Comment by Yinka71** [comment]
> Betul, update aja

Harus di rm -rf dulu gak kalo ada update an

**Comment by cholis321** [comment]
[ERR_MODULE_NOT_FOUND] maskudnya gimana ya?

**Comment by cholis321** [comment]
![Screenshot (254)](https://github.com/downygg/OceanClaimer/assets/166164368/e64de697-c6cb-4a15-b946-915f9246a993)

maksudnya gimana ya itu

**Comment by downygg** [comment]
> [ERR_MODULE_NOT_FOUND] maskudnya gimana ya?



> [ERR_MODULE_NOT_FOUND] maskudnya gimana ya?

npm i dulu

**Comment by downygg** [comment]
> > Betul, update aja
> 
> Harus di rm -rf dulu gak kalo ada update an



> > Betul, update aja
> 
> Harus di rm -rf dulu gak kalo ada update an

Bisa juga bir clean

**Comment by ahmad246642** [comment]
> > > Betul, update aja
> > 
> > 
> > Harus di rm -rf dulu gak kalo ada update an
> 
> > > Betul, update aja
> > 
> > 
> > Harus di rm -rf dulu gak kalo ada update an
> 
> Bisa juga bir clean
ada auto claim tiap 1 jam ga bang ato 2 jam

**Comment by ahmad246642** [comment]
bang bikin bot VivaFtn juga bang mayan tuh

**Comment by ahmad246642** [comment]
> > > Betul, update aja

punyaku yg 2 hour masih 1 menit bang claim nya

**Comment by downygg** [comment]
> > > > Betul, update aja
> 
> punyaku yg 2 hour masih 1 menit bang claim nya

Ada error ga?

**Comment by Yinka71** [comment]
> bang bikin bot VivaFtn juga bang mayan tuh

Iya babg setuju,,bikinin viva ftn

**Comment by ahmad246642** [comment]
> > > > > Betul, update aja
> > 
> > 
> > punyaku yg 2 hour masih 1 menit bang claim nya
> 
> Ada error ga?

gada bang btw dinerf njir wkwk

**Comment by Rafly-XD** [comment]
Iya bg buat bot viva ftn
