### ISSUE TITLE
Eror

### ISSUE THREAD

**Issue by Reydroo8282** [downygg/OceanClaimer#85]
![Screenshot_2024-05-27-23-29-22-49_84d3000e3f4017145260f7618db1d683](https://github.com/downygg/OceanClaimer/assets/170424563/2f4bd744-a594-40ed-a59a-5514e251cef5)

Itu kenapa ya bg eror

**Comment by Reydroo8282** [comment]
![Screenshot_2024-05-27-23-29-22-49_84d3000e3f4017145260f7618db1d683](https://github.com/downygg/OceanClaimer/assets/170424563/f9bda730-2029-498a-bcf4-274f1415010a)

**Comment by downygg** [comment]
Npm i dulu

**Comment by Reydroo8282** [comment]
Ok
