### ISSUE TITLE
Donet 0.1 sui

### ISSUE THREAD

**Issue by AsaaXV** [downygg/OceanClaimer#86]
Bang kok ane udah donet tapi gak bisa pake api key nya... Gmail anw imuhfatur@gmail.com

**Comment by AsaaXV** [comment]
Owh iya buatin juga web view biar bisa pake uptime view web... Fungsinya biar bisa jalan terus di replit

**Comment by downygg** [comment]
Kalo belum bisa di pake brrti email ny belum di acc. Share emsil disini berpotensi api key di pake org

**Comment by downygg** [comment]
> Bang kok ane udah donet tapi gak bisa pake api key nya... Gmail anw [imuhfatur@gmail.com](mailto:imuhfatur@gmail.com)

ini yg di input kok address tujuan ny, bukan txid nya. Isi ulang form ny pake email lain
