### ISSUE TITLE
update interval

### ISSUE THREAD

**Issue by ganjsmoke** [downygg/OceanClaimer#87]
![2 hour](https://github.com/downygg/OceanClaimer/assets/10595520/7412e6df-ef17-4f43-8de3-4a6f35f1bb02)
udah di set 2jam, tapi tetap check tiap 1 menit
![1menit](https://github.com/downygg/OceanClaimer/assets/10595520/95c3b38f-4347-4703-9935-b29c49b6fea5)
sot sure if this a bug or not

**Comment by downygg** [comment]
Status claim ny ada yg merah ?

**Comment by ganjsmoke** [comment]
tidak ada

**Comment by smadavv-airdrop** [comment]
bang tambahin delay custom, dan klo ada 1 yg error claim jgn jadi 1 menit bang biar aj ke skip

**Comment by downygg** [comment]
> tidak ada

berati akun nya udah di claim semua? behavior kalo delay 1 menit itu kalau ada error atau semua akun udh di claim yang menandakan tidak ada waktu tercepat maka looping kembali untuk mencari waktu tercepat.

**Comment by downygg** [comment]
> bang tambahin delay custom, dan klo ada 1 yg error claim jgn jadi 1 menit bang biar aj ke skip

error ny seperti apa ?
