### ISSUE TITLE
Donate 5SUI get api key

### ISSUE THREAD

**Issue by locduc071190** [downygg/OceanClaimer#94]
Sir, why can't I use the api key after I've done it... please check : jubrian195974@gmail.com

**Comment by downygg** [comment]
Send with new email, your api key is leaked

Pada Sabtu, 01 Juni 2024, locduc071190 ***@***.***> menulis:

**Comment by locduc071190** [comment]
yes sir. i will do it

**Comment by locduc071190** [comment]
please check

Vào Th 7, 1 thg 6, 2024 vào lúc 20:54 downygg ***@***.***>
đã viết:

**Comment by downygg** [comment]
approved
